server:
  port: 8081

#person:
#  lastname: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - wangwu
#    - xiaoming
#  dog:
#    name: 小猴
#    age: 2