
## 数据源配置
server:
  port: 8081
spring:
  datasource:
    username: root
    password: 709463253
    url: jdbc:mysql://localhost:3306/node?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.feiyu.model

